[package]
name = "neural_network"
version = "0.1.0"
edition = "2021"
[features]
default = ["rayon"]


[dependencies]
num = "0.4"
rand = "0.8"
anyhow = "1.0"

rayon = { version = "1.10", optional = true }
